### ISSUE TITLE
Webpack Fails

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#64]
```
> lockbox@0.1.0-pre build /Users/ssage/Documents/Projects/lockbox-extension
> webpack

/Users/ssage/Documents/Projects/lockbox-extension/webpack.config.babel.js:5
import webpack from "webpack";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at requireConfig (/Users/ssage/Documents/Projects/lockbox-extension/node_modules/webpack/bin/convert-argv.js:97:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lockbox@0.1.0-pre build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lockbox@0.1.0-pre build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ssage/.npm/_logs/2017-09-11T19_32_10_550Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lockbox@0.1.0-pre prerun: `npm run-script build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lockbox@0.1.0-pre prerun script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ssage/.npm/_logs/2017-09-11T19_32_10_578Z-debug.log
```
As observed by @devinreams

**Comment by jimporter** [comment]
Looks like babel isn't being run, although it works fine for me. Did you run `npm install` first?

**Comment by devinreams** [comment]
Steps leading up to this were:

- `git pull`
- `npm install`
- `npm run run` (webpack error)
- `npm i -g npm` (there is a new version, maybe that helps?)
- `npm run run` (webpack error)
- `rm -rf node_modules` (why not?)
- `npm install`
- `npm install -g webpack` (maybe?)

**Comment by jimporter** [comment]
It works fine for me on both production and development configs, and our CI is happy...

**Comment by devinreams** [comment]
We played with npm and ultimately another npm install in a new session made stuff work.

I uninstalled all my npm global packages (to make sure I didn't have anything special already installed) with a fresh repo clone (and install) and it seems to install and run fine.

Thanks for jumping on it. I think we're OK here..
